[package]
name = "localbar-tauri"
version = "0.2.0"
edition = "2021"

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { workspace = true }
localbar-core = { path = "../localbar-core" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", features = ["NSEvent", "NSApplication", "NSImage", "block2"] }
objc2-foundation = { version = "0.3.2", features = ["NSData"] }
block2 = "0.6.2"
