[package]
name = "localbar-tauri"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { workspace = true }
localbar-core = { path = "../localbar-core" }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sysinfo = { workspace = true }
tokio = { workspace = true }
